import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import localFonts from 'next/font/local'
import Headers from "./components/Header";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const FontJudul = localFonts({
  src: "./fonts/Gill_Sans_Bold.otf",
  weight: "7000",
  style: "normal",
  variable: "--font-judul",
});

const FontIsi = localFonts({
  src: "./fonts/Gill_Sans.otf",
  weight: "400",
  style: "normal",
  variable: "--font-isi",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: LayoutProps<"/">) {
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} ${FontJudul.variable} ${FontIsi.variable} h-full antialiased`}
    >
      
      <body className="min-h-full flex flex-col">
        <Headers />
        {children}
      </body>
    </html>
  );
}